name: Android CI for AOSP Pure Launcher- AOSP Flavor

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build AOSP Pure Launcher with Gradle (AOSP Flavor)
      run: mkdir -p /home/runner/work/AOSP-Pure-Launcher/AOSP-Pure-Launcher/build/extracted-protos/main && mkdir -p /home/runner/work/AOSP-Pure-Launcher/AOSP-Pure-Launcher/build/extracted-protos/aosp && mkdir -p /home/runner/work/AOSP-Pure-Launcher/AOSP-Pure-Launcher/build/extracted-protos/debug && mkdir -p /home/runner/work/AOSP-Pure-Launcher/AOSP-Pure-Launcher/build/extracted-protos/aospDebug && ./gradlew assembleAosp
